### ISSUE TITLE
High-fidelity wireframe (Initial design) - prototype version

### ISSUE THREAD

**Issue by devkurono** [chronohubtech/Taily#4]
## Design
We're making the design simple and cute as much as possible.

**Figma:** https://www.figma.com/file/SrhRzkbmyjtc3uyU1oIKDz/Taily?node-id=0%3A1

## Credits
The current logo is only for the placeholder (**nonmonetary usage**), placeholder will be replaced upon finishing our own brandmark/mascot.  Credits to [Puglie Pug](pugliepug.com) for the placeholder.

**Comment by devkurono** [comment]
### Default Theme

![Image](https://user-images.githubusercontent.com/68635840/200533304-9df670bc-70bc-46eb-9b2e-3c147b04fac2.png)



![Image](https://user-images.githubusercontent.com/68635840/200533320-123f2540-3a82-4fce-bb63-9f9121a54ba7.png)

**Comment by devkurono** [comment]
## Default Theme version 2

### What's new?
- Menu button 
- Clean/clear button moved to completed toggle

![Image](https://user-images.githubusercontent.com/68635840/200545350-5a4f111d-49d9-4c2b-adea-59cc21c92027.png)

**Comment by devkurono** [comment]
## Dark mode version 1


![Image](https://user-images.githubusercontent.com/68635840/200546275-9ca4bd1a-aac0-4f65-a342-ec588cae61a2.png)





![Image](https://user-images.githubusercontent.com/68635840/200546458-369064a2-22f4-4088-a559-a1fad6f28dc5.png)

**Comment by kyraidev** [comment]
Update authentication design:
- Email & password
- Google account auth
